language: node_js
node_js:
- v6.11.5
cache:
  directories:
  - node-modules
services:
  - mysql
before_script:
  - npm run build:database
  - npm run postinstall
# Travis CI automatically runs: npm install, npm start, npm test
