language: node_js
node_js:
- v6.11.5
cache:
  directories:
  - node-modules
services:
  - mysql
before_script:
  - npm run build:database
# Travis CI automatically runs: npm install, npm start, npm test
deploy:
  provider: heroku
  api_key:
    secure: nBVpXXkJcI2UU8Ll0UganmAV+t1TR673TBGlWQotbqj/FfmhbnI5Sa1cZMPyWrPsR4xgLy0zLwkIAFzn/2z/gfxbg/gDt0q3pmgn//yUtWIy6hlL6tN9lvKJl+wMqh8RcEJBd2d+y3kAPBPLWy0BKd7L+GwQQ565UZKllnh+7aDgQ4o9Os8DdTR4OxuV/zxjINh4XC81SfVpNaxV8qHbu3ntYewCJ0dG/rbDEspxTjnTxdpC+EQ3+vqScwbxloSgMSGhPUOBZVJ4N9dShR6+BbZRJKjGqCjtKN+Ellt48VOAixQPVg9Dz7KAPQJ4W+uwulxbshN0Tqv80BVQZLoQU2zEvoScgsAuIhOAyJrmppwVi23r86mOZKIXH3Lv7cDEogNMkFWCcGKDKh9DzWh8zKuYIfxWyo2daCEV+4lm45wWeCngT7OnyGJlsUUBKB2dWmtJjfGWXJrkuhRiVpyHCmam2u4pX2mOHDl+Mt4l5fcgubyqlnBfaW+hRSh48W7NkGSUfCwNLBNLatMGLUaTgrGZvV7ffz1N6g5QpcKGRe1nqNRBF3+i4n+ufXjiK6lQHDcemRzwnRgTUtKQulX5j99lfVY9PrMylyKS51950X4QuJfeheIuO16r131CYZkNTYTH3gb164YHzYcqsP6M9G0D0EcTmTYZ6ua/ELawOpw=
  app: yalp
